# Quick setup
# docker compose up

services:
  talker:
    image: microros/micro-ros-agent:humble
    command: serial -D /dev/ttyAMA0  serial -b 576000 # -v6
    devices:
      - /dev/ttyAMA0
    privileged: true

  listener:
    build: .
    command: ros2 run demo_nodes_cpp listener